using System;
using System.Collections.Generic;
using System.Linq;

namespace OniMcp.Tools
{
    public static partial class WorldEditorTools
    {
        private sealed class SymbolGlyphEntry
        {
            public string Kind;
            public string Id;
            public char Glyph;
            public string Name;
        }

        private static readonly IReadOnlyList<SymbolGlyphEntry> GeneratedGlyphEntries = ParseGeneratedGlyphRows();
        private static readonly Dictionary<string, SymbolGlyphEntry> GeneratedGlyphById = GeneratedGlyphEntries
            .GroupBy(e => e.Id, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

        private static IReadOnlyList<SymbolGlyphEntry> ParseGeneratedGlyphRows()
        {
            string rows = string.Concat(
            "Building|AdvancedApothecary|核|核能配药桌\nBuilding|AdvancedCraftingTable|焊|焊接台\nBuilding|AdvancedDoctorStation|病|病诊站\nBuilding|AdvancedResearchCenter|超|超级计算机\nBuilding|AirborneCreatureLure|飞|飞行小动物诱惑器\nBuilding|AirBorneCritterCondo|飞|飞行小动物公寓\nBuilding|AirConditioner|温|温度调节器\nBuilding|AirFilter|空|空气净化器\nBuilding|AlgaeDistillery|藻|藻类蒸馏器\nBuilding|AlgaeHabitat|盆|藻类箱\nBuilding|Apothecary|配|配药桌\nBuilding|ArcadeMachine|游|游戏机台\n",
            "Building|ArtifactAnalysisStation|工|工艺品分析站\nBuilding|ArtifactCargoBay|工|工艺品运输舱\nBuilding|AstronautTrainingCenter|太|太空学员离心机\nBuilding|AtomicGarden|原|原子花园\nBuilding|AutoMiner|自|自动采矿机\nBuilding|Battery|蓄|蓄电池\nBuilding|BatteryComplete|蓄|蓄电池\nBuilding|BatteryMedium|巨|巨型蓄电池\nBuilding|BatteryModule|蓄|蓄电池舱\nBuilding|BatterySmart|智|智能蓄电池\nBuilding|BeachChair|沙|沙滩椅\nBuilding|Bed|床|床铺\n",
            "Building|BedComplete|床|床铺\nBuilding|BiodieselEngine|生|生物柴油引擎\nBuilding|BiodieselEngineCluster|生|生物柴油引擎\nBuilding|BottleEmptier|液|液桶排倒器\nBuilding|BottleEmptierConduitGas|气|气罐抽出器\nBuilding|BottleEmptierConduitLiquid|液|液桶抽出器\nBuilding|BottleEmptierGas|气|气罐排倒器\nBuilding|BunkerDoor|地|地堡门\nBuilding|BunkerTile|地|地堡砖\nBuilding|Campfire|柴|柴火炉\nBuilding|Canvas|空|空白画布\nBuilding|CanvasTall|肖|肖像画布\n",
            "Building|CanvasWide|风|风景画布\nBuilding|CargoBay|货|货舱\nBuilding|CargoBayCluster|大|大型货舱\nBuilding|CarpetTile|地|地毯砖\nBuilding|CeilingFossilSculpture|垂|垂吊化石雕塑块\nBuilding|CeilingLight|吸|吸顶灯\nBuilding|Checkpoint|复|复制人检查站\nBuilding|ChemicalRefinery|乳|乳化器\nBuilding|Chlorinator|漂|漂白石料斗\nBuilding|ClothingAlterationStation|时|时装翻新器\nBuilding|ClothingFabricator|纺|纺织机\nBuilding|ClusterTelescope|望|望远镜\n",
            "Building|ClusterTelescopeEnclosed|隔|隔绝式望远镜\nBuilding|CO2Engine|二|二氧化碳引擎\nBuilding|CO2Scrubber|碳|碳素脱离器\nBuilding|CommandModule|指|指挥舱\nBuilding|Compost|堆|堆肥堆\nBuilding|ContactConductivePipeBridge|导|导热板\nBuilding|CookingStation|灶|电动烤炉\nBuilding|CornerMoulding|边|边角饰件\nBuilding|CosmicResearchCenter|科|虚拟天象仪\nBuilding|CraftingTable|工|工作台\nBuilding|CreatureAirTrap|飞|飞行小动物陷阱\nBuilding|CreatureDeliveryPoint|小|小动物放生点\n",
            "Building|CreatureFeeder|小|小动物喂食器\nBuilding|CreatureGroundTrap|小|小动物陷阱\nBuilding|CreatureTrap|小|小动物陷阱\nBuilding|CrewCapsule|乘|乘员舱\nBuilding|CritterCondo|小|小动物公寓\nBuilding|CritterDropOff|小|小动物放生点\nBuilding|CritterPickUp|小|小动物移取点\nBuilding|CrownMoulding|天|天花板饰件\nBuilding|DataMiner|数|数据挖掘仪\nBuilding|DecontaminationShower|除|除污淋浴隔间\nBuilding|Deepfryer|油|油炸锅\nBuilding|Desalinator|脱|脱盐器\n",
            "Building|DevGenerator|开|开发者发电机\nBuilding|DevHeater|开|开发者加热器\nBuilding|DevHEPSpawner|开|开发者辐射粒子生成器\nBuilding|DevLifeSupport|开|开发者维生器\nBuilding|DevLightGenerator|开|开发者光源\nBuilding|DevPumpGas|开|开发者气泵\nBuilding|DevPumpLiquid|开|开发者液泵\nBuilding|DevPumpSolid|开|开发者固体泵\nBuilding|DevRadiationGenerator|开|开发者辐射释放器\nBuilding|DiamondPress|钻|钻石压机\nBuilding|DiningTable|小|小餐桌\nBuilding|DLC1CosmicResearchCenter|虚|虚拟天象仪\n",
            "Building|DoctorStation|医|医务站\nBuilding|Door|门|气动门\nBuilding|EggCracker|敲|敲蛋桌\nBuilding|EggIncubator|孵|孵化器\nBuilding|ElectrobankCharger|移|移动电源充电机\nBuilding|Electrolyzer|解|电解器\nBuilding|EspressoMachine|浓|浓缩咖啡机\nBuilding|EthanolDistillery|乙|乙醇蒸馏器\nBuilding|ExobaseHeadquarters|舱|迷你舱\nBuilding|ExteriorWall|干|干板墙\nBuilding|FabricatedWoodMaker|胶|胶合板压机\nBuilding|FacilityBackWallWindow|窗|窗户\n",
            "Building|FarmStation|农|农业站\nBuilding|FarmTile|土|土培砖\nBuilding|FertilizerMaker|肥|肥料合成器\nBuilding|FirePole|杆|消防滑杆\nBuilding|FishDeliveryPoint|鱼|鱼类放生点\nBuilding|FishFeeder|喂|喂鱼器\nBuilding|FishPickUp|鱼|鱼类移取点\nBuilding|FishTrap|捕|捕鱼陷阱\nBuilding|FloorLamp|电|电灯\nBuilding|FloorSwitch|压|压力板\nBuilding|FlowerVase|花|花盆\nBuilding|FlowerVaseHanging|垂|垂吊花盆\n",
            "Building|FlowerVaseHangingFancy|透|透明花盆\nBuilding|FlowerVaseWall|墙|墙壁花盆\nBuilding|FlushToilet|厕|抽水马桶\nBuilding|FlyingCreatureBait|飞|飞行小动物诱饵\nBuilding|FoodDehydrator|脱|脱水机\nBuilding|FoodRehydrator|充|充水机\nBuilding|FossilDig|远|远古标本\nBuilding|FossilSculpture|化|化石雕塑块\nBuilding|Gantry|通|通行支架\nBuilding|GasBottler|气|气体装罐器\nBuilding|GasCargoBay|气|气罐货舱\nBuilding|GasCargoBayCluster|大|大型气罐货舱\n",
            "Building|GasCargoBaySmall|气|气罐货舱\nBuilding|GasConduit|管|气体管道\nBuilding|GasConduitBridge|桥|气体管桥\nBuilding|GasConduitOverflow|气|气体溢流阀\nBuilding|GasConduitPreferentialFlow|优|优先气流阀\nBuilding|GasConduitRadiant|导|导热气体管道\nBuilding|GasFilter|气|气体筛选器\nBuilding|GasLimitValve|气|气体计量阀\nBuilding|GasLogicValve|气|气体截断阀\nBuilding|GasMiniPump|小|小型气泵\nBuilding|GasPermeableMembrane|网|透气砖\nBuilding|GasPump|泵|气泵\n",
            "Building|GasReservoir|储|储气库\nBuilding|GasValve|气|气体调节阀\nBuilding|GasVent|出|排气口\nBuilding|GasVentHighPressure|高|高压排气口\nBuilding|Generator|发|煤炭发电机\nBuilding|GenericFabricator|全|全能打印机\nBuilding|GeneticAnalysisStation|植|植物分析仪\nBuilding|GeoTuner|地|地质调谐仪\nBuilding|GlassCeilingLight|玻|玻璃水母吸顶灯\nBuilding|GlassExteriorWall|玻|玻璃背景墙\nBuilding|GlassForge|玻|玻璃熔炉\nBuilding|GlassTile|窗|窗户砖\n",
            "Building|GourmetCookingStation|燃|燃气灶\nBuilding|Grave|雅|雅致的纪念碑\nBuilding|GravitasBathroomStall|马|马桶\nBuilding|GravitasContainer|睡|睡衣储柜\nBuilding|GravitasCreatureManipulator|小|小动物衍变器\nBuilding|GravitasDoor|庄|庄严科技门\nBuilding|GravitasLabLight|灯|LED灯\nBuilding|GravitasPedestal|庄|庄严科技基座\nBuilding|GunkEmptier|粘|粘渣油提取器\nBuilding|HabitatModuleMedium|太|太空员舱\nBuilding|HabitatModuleSmall|单|单太空员前锥\nBuilding|HandSanitizer|手|手部消毒站\n",
            "Building|Headquarters|舱|打印舱\nBuilding|HeadquartersComplete|舱|打印舱\nBuilding|HeatCompressor|液|液体均热器\nBuilding|HEPBattery|辐|辐射粒子蓄存器\nBuilding|HEPBridgeTile|辐|辐射粒子接合板\nBuilding|HEPEngine|辐|辐射粒子引擎\nBuilding|HighEnergyParticleRedirector|辐|辐射粒子变向器\nBuilding|HighEnergyParticleSpawner|辐|辐射粒子发生器\nBuilding|HighWattageWire|粗|高负荷电线\nBuilding|HijackedHeadquarters|打|打印截能仪\nBuilding|HotTub|热|热水浴缸\nBuilding|HushaCups|静|静杯花\n",
            "Building|HushBugPlantOriginal|静|静杯花\nBuilding|HydrogenEngine|液|液氢引擎\nBuilding|HydrogenEngineCluster|液|液氢引擎\nBuilding|HydrogenGenerator|氢|氢气发电机\nBuilding|HydroponicFarm|液|液培砖\nBuilding|IceCooledFan|冰|冰冷风扇\nBuilding|IceKettle|融|融冰壶\nBuilding|IceMachine|制|制冰机\nBuilding|IceSculpture|冰|冰雕塑块\nBuilding|InsulatedDoor|隔|隔热门\nBuilding|InsulatedGasConduit|隔|隔热气体管道\nBuilding|InsulatedLiquidConduit|隔|隔热液体管道\n",
            "Building|InsulationTile|隔|隔热砖\nBuilding|ItemPedestal|基|基座\nBuilding|JetSuitLocker|喷|喷气服存放柜\nBuilding|JetSuitMarker|喷|喷气服检查站\nBuilding|Juicer|榨|榨汁机\nBuilding|KeroseneEngine|石|石油引擎\nBuilding|KeroseneEngineCluster|石|石油引擎\nBuilding|KeroseneEngineClusterSmall|小|小型石油引擎\nBuilding|Kiln|窑|窑炉\nBuilding|Ladder|梯|梯子\nBuilding|LadderFast|梯|塑料梯子\nBuilding|LandingBeacon|定|定位信标\n",
            "Building|LargeBackwallFarm|墙|墙壁种植箱\nBuilding|LargeElectrobankDischarger|大|大型放电器\nBuilding|LaunchPad|火|火箭平台\nBuilding|LeadSuitLocker|铅|铅服存放柜\nBuilding|LeadSuitMarker|铅|铅服检查站\nBuilding|LiquidBottler|液|液体装桶器\nBuilding|LiquidCargoBay|液|液缸货舱\nBuilding|LiquidCargoBayCluster|大|大型液缸货舱\nBuilding|LiquidCargoBaySmall|液|液缸货舱\nBuilding|LiquidConditioner|液|液温调节器\nBuilding|LiquidConduit|管|液体管道\nBuilding|LiquidConduitBridge|桥|液体管桥\n",
            "Building|LiquidConduitOverflow|液|液体溢流阀\nBuilding|LiquidConduitPreferentialFlow|优|优先液流阀\nBuilding|LiquidConduitRadiant|导|导热液体管道\nBuilding|LiquidCooledFan|水|水冷风扇\nBuilding|LiquidFilter|液|液体筛选器\nBuilding|LiquidFuelTank|液|液缸燃料舱\nBuilding|LiquidFuelTankCluster|大|大型液缸燃料舱\nBuilding|LiquidHeater|液|液体加热器\nBuilding|LiquidLimitValve|液|液体计量阀\nBuilding|LiquidLogicValve|液|液体截断阀\nBuilding|LiquidMiniPump|小|小型液泵\nBuilding|LiquidPump|泵|液泵\n",
            "Building|LiquidPumpingStation|泵|手压泵\nBuilding|LiquidReservoir|储|储液库\nBuilding|LiquidValve|液|液体调节阀\nBuilding|LiquidVent|排|排液口\nBuilding|LogicDuplicantSensor|复|复制人运动传感器\nBuilding|LogicGateAND|与|与门\nBuilding|LogicGateBUFFER|缓|缓冲门\nBuilding|LogicGateDemultiplexer|信|信号分配器\nBuilding|LogicGateFILTER|过|过滤门\nBuilding|LogicGateMultiplexer|信|信号选择器\nBuilding|LogicGateNOT|非|非门\nBuilding|LogicGateOR|或|或门\n",
            "Building|LogicGateXOR|异|异或门\nBuilding|LogicInterasteroidReceiver|信|信号接收器\nBuilding|LogicInterasteroidSender|信|信号播报器\nBuilding|LogicRibbon|信|信号线组\nBuilding|LogicRibbonBridge|信|信号线组桥\nBuilding|LogicWire|信|信号线\nBuilding|LogicWireBridge|桥|信号线桥\nBuilding|LonelyMailBox|邮|邮箱\nBuilding|LonelyMinionHouse|庄|庄严科技运输集装箱\nBuilding|LuxuryBed|床|舒适的床\nBuilding|MachineShop|机|机械站\nBuilding|ManualGenerator|轮|人力发电机\n",
            "Building|ManualGeneratorComplete|轮|人力发电机\nBuilding|ManualHighEnergyParticleSpawner|人|人力辐射粒子发生器\nBuilding|ManualPressureDoor|门|手动气闸\nBuilding|MarbleSculpture|大|大理石雕塑块\nBuilding|MassageTable|按|按摩床\nBuilding|MassiveHeatSink|反|反熵热量中和器\nBuilding|MechanicalSurfboard|机|机械冲浪板\nBuilding|MedicalCot|分|分诊床\nBuilding|MegaBrainTank|梦|梦境合成仪\nBuilding|MercuryCeilingLight|汞|汞吸顶灯\nBuilding|MeshTile|筛|网格砖\nBuilding|MeshTileComplete|筛|网格砖\n",
            "Building|MetalRefinery|金|金属精炼器\nBuilding|MetalSculpture|金|金属雕塑块\nBuilding|MetalTile|金|金属砖\nBuilding|MethaneGenerator|天|天然气发电机\nBuilding|MicrobeMusher|捏|食物压制器\nBuilding|MilkFatSeparator|提|提炼器\nBuilding|MilkFeeder|小|小动物直饮器\nBuilding|MilkingStation|挤|挤奶站\nBuilding|MilkPress|植|植物粉碎机\nBuilding|MineralDeoxidizer|散|氧气扩散器\nBuilding|MineralDeoxidizerComplete|散|氧气扩散器\nBuilding|MiniFridge|小|小型冰箱\n",
            "Building|MissileFabricator|爆|爆破弹组装机\nBuilding|MissileLauncher|流|流星爆破炮\nBuilding|MissionControl|航|航天指挥站\nBuilding|MissionControlCluster|航|航天指挥站\nBuilding|ModularLaunchpadPortBridge|火|火箭端口延伸桥\nBuilding|ModularLaunchpadPortGas|火|火箭端口气体装载器\nBuilding|ModularLaunchpadPortGasUnloader|火|火箭端口气体卸载器\nBuilding|ModularLaunchpadPortLiquid|火|火箭端口液体装载器\nBuilding|ModularLaunchpadPortLiquidUnloader|火|火箭端口液体卸载器\nBuilding|ModularLaunchpadPortSolid|火|火箭端口固体装载器\nBuilding|ModularLaunchpadPortSolidUnloader|火|火箭端口固体卸载器\nBuilding|MonumentBottom|丰|丰碑底基\n",
            "Building|MonumentMiddle|丰|丰碑中段\nBuilding|MonumentTop|丰|丰碑顶部\nBuilding|MorbRoverMaker|生|生机组构仪\nBuilding|MouldingTile|镶|镶边砖\nBuilding|MultiMinionDiningTable|公|公用餐桌\nBuilding|Mussel_Sprout_Original|贻|贻贝芽\nBuilding|MusselSproutOriginal|贻|贻贝芽\nBuilding|NoseconeBasic|基|基础前锥\nBuilding|NoseconeHarvest|钻|钻头前锥\nBuilding|NuclearReactor|研|研究性反应堆\nBuilding|NuclearResearchCenter|材|材料研究终端\nBuilding|ObjectDispenser|自|自动卸物箱\n",
            "Building|OilChanger|润|润滑站\nBuilding|OilRefinery|原|原油精炼器\nBuilding|OilWellCap|油|油井\nBuilding|OrbitalCargoModule|环|环轨货舱\nBuilding|OrbitalResearchCenter|轨|轨道数据收集实验仪\nBuilding|OreScrubber|矿|矿石洗涤器\nBuilding|Outhouse|厕|户外厕所\nBuilding|OuthouseComplete|厕|户外厕所\nBuilding|OxidizerTank|固|固体氧化剂舱\nBuilding|OxidizerTankCluster|大|大型固体氧化剂舱\nBuilding|OxidizerTankLiquid|液|液体氧化剂舱\nBuilding|OxidizerTankLiquidCluster|液|液体氧化剂舱\n",
            "Building|OxygenMaskLocker|氧|氧气面罩存放柜\nBuilding|OxygenMaskMarker|氧|氧气面罩检查站\nBuilding|OxygenMaskStation|氧|氧气面罩站\nBuilding|OxyliteRefinery|氧|氧石精炼炉\nBuilding|Oxysconce|氧|氧石烛台\nBuilding|ParkSign|公|公园标识\nBuilding|PeatGenerator|泥|泥炭燃烧器\nBuilding|PetroleumGenerator|石|石油发电机\nBuilding|Phonobox|点|点唱机器人\nBuilding|PioneerModule|先|先锋舱\nBuilding|PlanterBox|种|种植箱\nBuilding|PlasticTile|塑|塑料砖\n",
            "Building|POIDlc2ShowroomDoor|展|展厅门\nBuilding|POIFacilityDoor|大|大厅门\nBuilding|Polymerizer|聚|聚合物压塑器\nBuilding|PowerControlStation|电|电控站\nBuilding|PowerTransformer|变|大型变压器\nBuilding|PowerTransformerSmall|变|变压器\nBuilding|PressureDoor|门|机械气闸\nBuilding|PropBeachChair|破|破旧的沙滩椅\nBuilding|PropGravitasLabWall|实|实验室墙面\nBuilding|PropGravitasLabWindow|实|实验室窗户\nBuilding|PropGravitasLabWindowHorizontal|实|实验室窗户\nBuilding|PropGravitasWall|墙|墙面\n",
            "Building|PropGravitasWallPurple|墙|墙面\nBuilding|PropGravitasWallPurpleWhiteDiagonal|墙|墙面\nBuilding|RadiationLight|辐|辐射灯\nBuilding|RailGun|星|星际发射器\nBuilding|RailGunPayloadOpener|载|载货拆包器\nBuilding|RanchStation|梳|梳理站\nBuilding|RationBox|口|口粮箱\nBuilding|ReefGenerator|潮|潮汐涡轮机\nBuilding|Refrigerator|冰|冰箱\nBuilding|ResearchCenter|研|研究站\nBuilding|ResearchCenterComplete|研|研究站\nBuilding|ResearchClusterModule|研|研究舱\n",
            "Building|ResearchModule|研|研究舱\nBuilding|ResetSkillsStation|技|技能涤除器\nBuilding|RoboPilotCommandModule|机|机器驾驶舱\nBuilding|RoboPilotModule|机|机器驾驶舱\nBuilding|RockCrusher|碎|碎石机\nBuilding|RocketEnvelopeWindowTile|火|火箭窗户\nBuilding|RocketInteriorGasInput|气|气体输入配件\nBuilding|RocketInteriorGasInputPort|太|太空员舱气体输入端口\nBuilding|RocketInteriorGasOutput|气|气体输出配件\nBuilding|RocketInteriorGasOutputPort|太|太空员舱气体输出端口\nBuilding|RocketInteriorLiquidInput|液|液体输入配件\nBuilding|RocketInteriorLiquidInputPort|太|太空员舱液体输入端口\n",
            "Building|RocketInteriorLiquidOutput|液|液体输出配件\nBuilding|RocketInteriorLiquidOutputPort|太|太空员舱液体输出端口\nBuilding|RocketInteriorPowerPlug|电|电源插座配件\nBuilding|RocketInteriorSolidInput|运|运输存放配件\nBuilding|RocketInteriorSolidOutput|运|运输装载配件\nBuilding|RocketWallTile|火|火箭墙体\nBuilding|RoleStation|技|技能公示板\nBuilding|RubberMaker|硫|硫化器\nBuilding|RustDeoxidizer|铁|铁锈脱氧机\nBuilding|Sauna|桑|桑拿房\nBuilding|ScannerModule|制|制图舱\nBuilding|ScoutModule|侦|侦察舱\n",
            "Building|Sculpture|大|大型雕塑块\nBuilding|SeaLettuce_Original|草|水草\nBuilding|SeaLettuceOriginal|草|水草\nBuilding|ShearingStation|修|修剪站\nBuilding|Shelf|陈|陈列架\nBuilding|SludgePress|泥|泥浆分离器\nBuilding|SmallElectrobankDischarger|袖|袖珍放电器\nBuilding|SmallOxidizerTank|小|小型固体氧化剂舱\nBuilding|SmallSculpture|雕|雕塑块\nBuilding|Smoker|熏|熏炉\nBuilding|SnowTile|雪|雪砖\nBuilding|SodaFountain|汽|汽水机\n",
            "Building|Sodicane_Original|蔗|咸蔗\nBuilding|SodicaneOriginal|蔗|咸蔗\nBuilding|SolarPanel|太|太阳能板\nBuilding|SolarPanelModule|太|太阳能舱\nBuilding|SolidBooster|固|固体燃料推进器\nBuilding|SolidCargoBaySmall|货|货舱\nBuilding|SolidConduit|轨|运输轨道\nBuilding|SolidConduitBridge|桥|运输轨桥\nBuilding|SolidConduitInbox|运|运输装载器\nBuilding|SolidConduitOutbox|运|运输存放器\nBuilding|SolidFilter|固|固体筛选器\nBuilding|SolidLimitValve|轨|轨道计量器\n",
            "Building|SolidLogicValve|轨|轨道截断器\nBuilding|SolidTransferArm|自|自动清扫器\nBuilding|SolidVent|轨|轨道滑槽\nBuilding|SpaceHeater|空|空间加热器\nBuilding|SpecialCargoBay|生|生物货舱\nBuilding|SpecialCargoBayCluster|小|小动物货舱\nBuilding|SpiceGrinder|香|香料研磨器\nBuilding|SteamEngine|蒸|蒸汽引擎\nBuilding|SteamEngineCluster|蒸|蒸汽引擎\nBuilding|SteamTurbine|弃|[弃用] 蒸汽涡轮机\nBuilding|StorageLocker|存|存储箱\nBuilding|StorageLockerComplete|存|存储箱\n",
            "Building|StorageLockerSmart|储|智能存储箱\nBuilding|StorageTile|存|存储砖\nBuilding|SublimationStation|升|升华站\nBuilding|SugarEngine|糖|糖素引擎\nBuilding|SuitFabricator|太|太空服锻造台\nBuilding|SuitLocker|气|气压服存放柜\nBuilding|SuitMarker|气|气压服检查站\nBuilding|SunLamp|日|日光灯\nBuilding|SupermaterialRefinery|分|分子熔炉\nBuilding|SushiBar|寿|寿司台\nBuilding|SweepBotStation|扫|扫扫基站\nBuilding|Telephone|共|共线电话\n",
            "Building|TeleportalPad|传|传送台\nBuilding|Telescope|望|望远镜\nBuilding|TemporalTearOpener|时|时间裂口开放器\nBuilding|ThermalBlock|变|变温板\nBuilding|Tile|砖|砖块\nBuilding|TileComplete|砖|砖块\nBuilding|TouristModule|观|观光舱\nBuilding|TravelTube|运|运载管道\nBuilding|TravelTubeEntrance|运|运载管道入口\nBuilding|TravelTubeWallBridge|运|运载管道渡口\nBuilding|UnderwaterBreathingStation|呼|呼吸站\nBuilding|UnderwaterCritterCondo|水|水生小动物公寓\n",
            "Building|UnderwaterMilkFeeder|水|水生小动物直饮器\nBuilding|UnderwaterMilkingStation|水|水生挤奶站\nBuilding|UnderwaterRanchStation|水|水生梳理站\nBuilding|UnderwaterShearingStation|水|水生修剪站\nBuilding|UnderwaterVentDrill|海|海洋钻机\nBuilding|UraniumCentrifuge|铀|铀素离心机\nBuilding|VerticalWindTunnel|垂|垂直风洞\nBuilding|WallToilet|墙|墙排马桶\nBuilding|WarpConduitReceiver|供|供给传送器输出端\nBuilding|WarpConduitSender|供|供给传送器输入端\nBuilding|WashBasin|洗|洗手盆\nBuilding|WashBasinComplete|洗|洗手盆\n",
            "Building|WashSink|洗|洗手池\nBuilding|WaterCooler|饮|饮水机\nBuilding|WaterPurifier|净|净水器\nBuilding|WaterTrap|捕|捕鱼陷阱\nBuilding|WideFarmTile|宽|宽液培砖\nBuilding|Wire|线|电线\nBuilding|WireBridge|桥|电线桥\nBuilding|WireBridgeHighWattage|桥|高负荷电线接合板\nBuilding|WireRefined|线|导线\nBuilding|WireRefinedHighWattage|高|高负荷导线\nBuilding|WireRubber|绝|绝缘导线\nBuilding|WoodenDoor|柳|柳条门\n",
            "Building|WoodGasGenerator|木|木材燃烧器\nBuilding|WoodSculpture|木|木雕塑块\nBuilding|WoodStorage|柴|柴堆\nBuilding|WoodTile|木|木砖\nElement|Aerogel|气|气凝胶\nElement|Algae|藻|藻类\nElement|Aluminum|铝|铝\nElement|AluminumGas|气|气态铝\nElement|AluminumOre|铝|铝矿\nElement|Amber|琥|琥珀\nElement|Basalt|玄|玄武岩\nElement|Bitumen|沥|沥青\n",
            "Element|BleachStone|漂|漂白石\nElement|Brick|红|红砖\nElement|Brine|咸|浓盐水\nElement|BrineIce|浓|浓盐冰\nElement|Carbon|煤|煤炭\nElement|CarbonDioxide|碳|二氧化碳\nElement|CarbonFibre|碳|碳纤维\nElement|CarbonGas|气|气态碳\nElement|Cement|水|水泥\nElement|CementMix|水|水泥混合料\nElement|Ceramic|陶|陶瓷\nElement|Chlorine|液|液态氯\n",
            "Element|ChlorineGas|氯|氯气\nElement|Cinnabar|朱|朱砂矿\nElement|Clay|粘|粘土\nElement|Cobalt|钴|钴\nElement|CobaltGas|气|气态钴\nElement|Cobaltite|钴|钴矿\nElement|COMPOSITION|复|复合物\nElement|ContaminatedOxygen|污|污染氧\nElement|Copper|铜|铜\nElement|CopperGas|气|气态铜\nElement|Coquina|壳|壳灰岩\nElement|Corallium|珊|珊瑚质\n",
            "Element|Corium|堆|堆芯熔融物\nElement|Creature|遗|遗传生物软泥\nElement|CrudeOil|油|原油\nElement|CrushedIce|碎|碎冰\nElement|CrushedRock|碎|碎岩\nElement|Cuprite|铜|铜矿\nElement|DepletedUranium|贫|贫铀\nElement|Diamond|钻|钻石\nElement|Dirt|土|泥土\nElement|DirtyIce|冰|污染冰\nElement|DirtyWater|污|污染水\nElement|Electrum|银|银金矿\n",
            "Element|EnrichedUranium|浓|浓缩铀\nElement|Ethanol|乙|乙醇\nElement|EthanolGas|气|气态乙醇\nElement|FabricatedWood|胶|胶合板\nElement|Fallout|核|核尘埃\nElement|Fertilizer|肥|肥料\nElement|FishMilk|卵|卵浆\nElement|FishMilkIce|凝|凝冻卵浆\nElement|FoolsGold|黄|黄铁矿\nElement|Fossil|化|化石\nElement|FrozenInk|凝|凝冻鱿鱼墨汁\nElement|FrozenPhytoOil|凝|凝冻植物润滑油\n",
            "Element|Fullerene|富|富勒烯\nElement|Galena|方|方铅矿\nElement|Glass|玻|玻璃\nElement|Gold|金|金\nElement|GoldAmalgam|金|金汞齐\nElement|GoldGas|气|气态金\nElement|Granite|花|花岗岩\nElement|Graphite|石|石墨\nElement|Gunk|固|固态粘渣油\nElement|HardPolypropylene|塑|塑料质\nElement|Helium|氦|氦气\nElement|Hydrogen|氢|氢气\n",
            "Element|Ice|冰|冰\nElement|IgneousRock|火|火成岩\nElement|Ink|鱿|鱿鱼墨汁\nElement|Iridium|铱|铱\nElement|IridiumGas|气|气态铱\nElement|Iron|铁|铁\nElement|IronGas|气|气态铁\nElement|IronOre|铁|铁矿\nElement|Isoresin|异|异构树液\nElement|Katairite|深|深渊晶石\nElement|Latex|胶|胶乳\nElement|Lead|铅|铅\n",
            "Element|LeadGas|气|气态铅\nElement|Lime|石|石灰\nElement|LiquidCarbonDioxide|液|液态二氧化碳\nElement|LiquidGunk|粘|粘渣油\nElement|LiquidHelium|液|液态氦\nElement|LiquidHydrogen|氢|液态氢\nElement|LiquidMethane|液|液态甲烷\nElement|LiquidOxygen|氧|液态氧\nElement|LiquidPhosphorus|液|液态磷\nElement|LiquidPropane|液|液态丙烷\nElement|LiquidSulfur|液|液态硫\nElement|MaficRock|镁|镁铁质岩\n",
            "Element|Magma|岩|岩浆\nElement|Mercury|汞|汞\nElement|MercuryGas|汞|汞蒸气\nElement|Methane|瓦|天然气\nElement|Milk|咸|咸乳\nElement|MilkFat|咸|咸乳蜡\nElement|MilkIce|凝|凝冻咸乳\nElement|MoltenAluminum|熔|熔融铝\nElement|MoltenCarbon|熔|熔融碳\nElement|MoltenCobalt|熔|熔融钴\nElement|MoltenCopper|熔|熔融铜\nElement|MoltenGlass|熔|熔融玻璃\n",
            "Element|MoltenGold|熔|熔融金\nElement|MoltenIridium|熔|熔融铱\nElement|MoltenIron|熔|熔融铁\nElement|MoltenLead|熔|熔融铅\nElement|MoltenNickel|熔|熔融镍\nElement|MoltenNiobium|熔|熔融铌\nElement|MoltenSalt|熔|熔融盐\nElement|MoltenSteel|熔|熔融钢\nElement|MoltenSucrose|熔|熔融蔗糖\nElement|MoltenSyngas|熔|熔融合成气\nElement|MoltenTungsten|熔|熔融钨\nElement|MoltenUranium|熔|熔融铀\n",
            "Element|MoltenZinc|熔|熔融锌\nElement|Mucus|粘|粘蛋白\nElement|Mud|泥|泥巴\nElement|MurkyBrine|污|污染浓盐水\nElement|MurkyBrineIce|污|污染浓盐冰\nElement|Naphtha|液|液态石脑油\nElement|NaturalResin|树|树脂\nElement|NaturalSolidResin|固|固态树脂\nElement|Nickel|镍|镍\nElement|NickelGas|气|气态镍\nElement|NickelOre|镍|镍矿\nElement|Niobium|铌|铌\n",
            "Element|NiobiumGas|气|气态铌\nElement|NuclearWaste|液|液态核废料\nElement|Obsidian|黑|黑曜石\nElement|Oxygen|氧|氧气\nElement|OxyRock|氧|氧石\nElement|PalmWood|粘|粘胶木材\nElement|Pearl|珍|珍珠\nElement|Peat|泥|泥炭\nElement|Petroleum|油|石油\nElement|PhosphateNodules|磷|磷酸盐结晶\nElement|Phosphorite|磷|磷矿\nElement|Phosphorus|精|精炼磷\n",
            "Element|PhosphorusGas|气|气态磷\nElement|PhytoOil|植|植物润滑油\nElement|Polypropylene|塑|塑料\nElement|Propane|丙|丙烷\nElement|Radium|镭|镭\nElement|RefinedCarbon|精|精炼碳\nElement|RefinedLipid|生|生物柴油\nElement|Regolith|浮|浮土\nElement|Resin|树|树液\nElement|RockGas|气|气态岩\nElement|Rubber|橡|橡胶\nElement|Rust|铁|铁锈\n",
            "Element|Salt|盐|盐\nElement|SaltGas|气|气态盐\nElement|SaltWater|盐|盐水\nElement|Sand|沙|沙子\nElement|SandCement|水|砂水泥\nElement|SandStone|砂|砂岩\nElement|SedimentaryRock|沉|沉积岩\nElement|Shale|页|页岩\nElement|SiltStone|粉|粉砂岩\nElement|Slabs|建|建筑板材\nElement|SlimeMold|菌|菌泥\nElement|Snow|雪|雪\n",
            "Element|SolidCarbonDioxide|固|固态二氧化碳\nElement|SolidChlorine|固|固态氯\nElement|SolidCrudeOil|固|固态原油\nElement|SolidEthanol|固|固态乙醇\nElement|SolidHydrogen|固|固态氢\nElement|SolidMercury|固|固态汞\nElement|SolidMethane|固|固态甲烷\nElement|SolidMucus|凝|凝冻粘蛋白\nElement|SolidNaphtha|固|固态石脑油\nElement|SolidNuclearWaste|固|固态核废料\nElement|SolidOxygen|固|固态氧\nElement|SolidPetroleum|固|固态石油\n",
            "Element|SolidPropane|固|固态丙烷\nElement|SolidResin|固|固态树液\nElement|SolidSuperCoolant|固|固态超级冷却剂\nElement|SolidSyngas|固|固态合成气\nElement|SolidViscoGel|固|固态粘性凝胶\nElement|SourGas|高|高硫天然气\nElement|StableSnow|紧|紧压雪\nElement|Steam|汽|蒸汽\nElement|Steel|钢|钢\nElement|SteelGas|气|气态钢\nElement|Sucrose|蔗|蔗糖\nElement|SugarWater|花|花蜜\n",
            "Element|Sulfur|硫|硫\nElement|SulfurGas|硫|硫蒸气\nElement|SuperCoolant|超|超级冷却剂\nElement|SuperCoolantGas|气|气态超级冷却剂\nElement|SuperInsulator|隔|隔热质\nElement|Syngas|合|合成气\nElement|Tallow|动|动物油脂\nElement|TempConductorSolid|导|导热质\nElement|ToxicMud|污|污染泥\nElement|ToxicSand|污|污染土\nElement|Tungsten|钨|钨\nElement|TungstenGas|气|气态钨\n",
            "Element|Unobtanium|中|中子质\nElement|UraniumOre|铀|铀矿\nElement|Vacuum|.|真空\nElement|ViscoGel|粘|粘性凝胶流体\nElement|Void|虚|虚空\nElement|Water|水|水\nElement|Wolframite|黑|黑钨矿\nElement|WoodLog|木|木材\nElement|Yellowcake|黄|黄饼\nElement|Zinc|锌|锌\nElement|ZincGas|气|气态锌\nElement|ZincOre|锌|锌矿\n",
            "Entity|BionicMinion|仿|仿生人\nEntity|Critter|物|小动物\nEntity|Minion|人|复制人\n");
            var result = new List<SymbolGlyphEntry>();
            foreach (string row in rows.Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries))
            {
                string[] parts = row.Split('|');
                if (parts.Length < 4 || string.IsNullOrEmpty(parts[2]))
                    continue;
                result.Add(new SymbolGlyphEntry { Kind = parts[0], Id = parts[1], Glyph = parts[2][0], Name = parts[3] });
            }
            return result;
        }
    }
}
